task: detection

seed: 42

dataset:
  root_dir: "../../Face.v1i.coco"
  train:
    img_dir: "train"
    ann_file: "train/_annotations.coco.json"
  val:
    img_dir: "valid"
    ann_file: "valid/_annotations.coco.json"
  test:
    img_dir: "test"
    ann_file: "test/_annotations.coco.json"

model:
  class_names:
    - Face Detection - v1 V1
    - face
  pretrained_weights: "../rf-detr-base.pth"

train:
  num_epochs: 5
  batch_size: 4
  grad_accum_steps: 1
  lr: 0.0001
  weight_decay: 0.0001
  num_workers: 2
  device: cuda
  # resultion should be divisible by 56 for rfdetr
  resolution: 560
  amp: true

output:
  dir: "../outputs"
  run_name: "rfdetr_face_detection"
  final_model_name: "rfdetr_face_detection_model.pth"
  save_config_copy: true
