task: segmentation

seed: 42

dataset:
  root_dir: "D:/OneDrive - Imagevision.ai India Pvt Ltd/Prospects/Digioptics/Dataset/V1/combine/digioptics-dataset-coco-v1"
  train:
    img_dir: "train"
    ann_file: "train/_annotations.coco.json"
  val:
    img_dir: "valid"
    ann_file: "valid/_annotations.coco.json"
  test:
    img_dir: "test"
    ann_file: "test/_annotations.coco.json"

model:
  variant: nano
  class_names:
    - scalpel
    - clamp
    - straight_scissor
    - curved_scissor
  pretrained_weights: auto
  segmentation_head: true

train:
  num_epochs: 5
  batch_size: 2
  grad_accum_steps: 1
  lr: 0.0001
  weight_decay: 0.0001
  num_workers: 2
  device: cuda
  resolution: 480
  amp: true
  # set to auto to resume from outputs/<run_name>/checkpoint.pth if it exists
  resume: null

output:
  dir: "outputs"
  run_name: "rfdetr_digioptics-v1"
  final_model_name: "rf_detr_digioptics_model-v1.pth"
  save_config_copy: true
